Repository superfly/flyctl, pull requests merged in 2023-04, with the labels that each got.

#1983 V2 fly scale count
  internal/command/scale/count.go
  internal/command/scale/count_machines.go
  internal/command/scale/count_machines_test.go
  internal/command/scale/machine_defaults.go
  internal/command/scale/scale.go
  internal/command/scale/show_machines.go
Labels: apps-v2

#2060 `deploy`: hint to users when the release command machine exhausts their machine limit
  internal/command/deploy/machines_deploymachinesapp.go
Labels: ux, apps-v2

#2081 `deploy`: prefix machine updates with [n/total]
  internal/command/deploy/machines_deploymachinesapp.go
  internal/command/deploy/machines_releasecommand.go
  internal/machine/leasable_machine.go
Labels: enhancement, ux, apps-v2

#2058 `migrate-to-v2`: support apps with volumes
  api/machine_types.go
  api/resource_volumes.go
  api/types.go
  gql/schema.graphql
  internal/appconfig/config.go
  internal/command/migrate_to_v2/machines.go
  internal/command/migrate_to_v2/migrate_to_v2.go
  internal/command/migrate_to_v2/nomad.go
  internal/command/migrate_to_v2/pg.go
  internal/command/migrate_to_v2/volumes.go
  internal/command/volumes/destroy.go
  scripts/bump_version.sh
  test/preflight/apps_v2_integration_test.go
Labels: feature, apps-v2

#2086 Mounts per process group
  internal/appconfig/config.go
  internal/appconfig/config_test.go
  internal/appconfig/definition_test.go
  internal/appconfig/from_machine_set.go
  internal/appconfig/machines.go
  internal/appconfig/machines_test.go
  internal/appconfig/patches.go
  internal/appconfig/processgroups.go
  internal/appconfig/serde_test.go
  internal/appconfig/setters.go
  internal/appconfig/setters_test.go
  internal/appconfig/testdata/tomachine-mounts.toml
  internal/command/deploy/deploy.go
  internal/command/deploy/deploy_first.go
  internal/command/deploy/machines.go
  internal/command/deploy/machines_launchinput.go
  internal/command/deploy/machines_launchinput_test.go
  internal/command/deploy/machines_test.go
  internal/command/launch/sourceinfo.go
  internal/command/launch/srcinfo.go
  internal/command/migrate_to_v2/migrate_to_v2.go
  internal/command/migrate_to_v2/volumes.go
  internal/command/turboku/turboku.go
  test/preflight/fly_launch_test.go
Labels: feature, apps-v2

#2085 query homebrew cli for version info if installed through brew
  internal/command/version/update.go
  internal/update/update.go
Labels: bug, ux

#2101 `migrate-to-v2`: gate volume code behind whether we're using volumes
  internal/command/migrate_to_v2/migrate_to_v2.go
Labels: bug, apps-v2

#2102 `deploy`: promote group-less machines into "app" group
  internal/command/deploy/machines.go
Labels: bug, apps-v2

#2110 [v2] Set FLY_PROCESS_GROUP envvar
  internal/appconfig/machines.go
  internal/appconfig/machines_test.go
  internal/command/deploy/machines_launchinput_test.go
  internal/command/deploy/machines_test.go
Labels: apps-v2

#2145 Split dockerfile scan out so explicit launches don't use scanners
  internal/command/launch/sourceinfo.go
  scanner/dockerfile.go
  scanner/helpers.go
Labels: bug, from-the-forum

#2147 add `apps set-platform-version` for manual migration
  gql/generated.go
  internal/command/apps/apps.go
  internal/command/apps/set_platform_version.go
Labels: feature, apps-v2, from-the-forum

#2173 Fix `LoadAppNameIfPresent` by using correct error in `RequireAppName`
  internal/command/command.go
Labels: bug, from-the-forum

#2118 Add metrics
  flaps/flaps.go
  internal/build/imgsrc/buildpacks_builder.go
  internal/build/imgsrc/builtin_builder.go
  internal/build/imgsrc/docker.go
  internal/build/imgsrc/dockerfile_builder.go
  internal/cli/cli.go
  internal/command/command.go
  internal/command/deploy/deploy.go
  internal/command/deploy/deploy_build.go
  internal/command/launch/launch.go
  internal/config/config.go
  internal/config/file.go
  internal/metrics/api.go
  internal/metrics/helpers.go
  internal/metrics/token.go
Labels: enhancement

#2177 proxy_proto_options, default_self_signed for services and http_service
  api/machine_types.go
  internal/appconfig/definition_test.go
  internal/appconfig/serde_test.go
  internal/appconfig/service.go
  internal/appconfig/testdata/full-reference.toml
Labels: enhancement, apps-v2
