Repository superfly/flyctl, pull requests merged in 2023-03, with the labels that each got.

#1795 Fix `fly launch` not saving the chosen region
  internal/command/deploy/deploy.go
  internal/command/launch/launch.go
Labels: bug, apps-v2

#1799 deprecate `fly domains`, remove `fly domains register`
  cmd/domains.go
  docstrings/gen.go
  helpgen/flyctlhelp.toml
Labels: from-the-forum

#1810 "Release command" machine won't get mounts, metrics, services, checks and statics
  internal/command/deploy/machines.go
  internal/command/deploy/machines_test.go
Labels: bug, apps-v2

#1818 Pass environment variables to `nixpacks` with --env
  internal/build/imgsrc/nixpacks_builder.go
Labels: from-the-forum

#1823 More test cases for resolveUpdateMachineConfig
  internal/command/deploy/machines.go
  internal/command/deploy/machines_test.go
Labels: apps-v2

#1891 `fly machines run`: avoid nil deref when there's no fly.toml in cwd
  internal/appconfig/config.go
  internal/appconfig/config_test.go
Labels: bug

#1897 `fly env`: init flaps client before pulling remote config
  internal/command/checks/list.go
  internal/command/config/env.go
  internal/command/status/status.go
Labels: bug

#1903 `machine run`: always stop the spinner
  internal/command/machine/run.go
Labels: bug

#1918 `deploy`: fix bug in display of removed machines
  internal/command/deploy/machines.go
  test/preflight/apps_v2_integration_test.go
Labels: bug

#1974 fix: Add latlon to platform regions
  api/resource_platform.go
Labels: bug
